porzotokProject/porzotokProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('', include('porzotokApp.urls')),
    path('', include('HotelAdmin.urls')),
    path('', include('androidAPI_V1.urls')),
    url('^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
	url('^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]

porzotokProject/webapp/urls.py
from django.urls import path, include
from webapp import views
app_name = 'webapp'
urlpatterns = [
    # frontend views urls start
    # home view urls
    path('', views.HomeView.as_view(), name='home'),
    # single hotel view urls
    path('hotel/<str:hotel_slug>/', views.SingleHotelView.as_view(), name='single-hotel'),
    # Checkout urls
    path('checkout/', views.CheckOutView.as_view(), name='checkout'),
    path('city-info/<str:city_slug>/', views.SingleCityView.as_view(), name='city_info'),
    path('spot-info/<str:spots_slug>/', views.SpotSingleView.as_view(), name='spot-info'),
    # Search URL
    path('search/', views.SearchView.as_view(), name='search'),
    # show cart details
    path('show-cart/', views.CartSView.as_view(), name='show_cart'),
    # front end customer/user registration 
    path('user-register/', views.UserRegistrationView.as_view(), name='user_register'),
    # front end customer/user login 
    path('user-login/', views.UserLoginView.as_view(), name='user_login'),
    # front end customer/user logoutt 
    path('user-logout/', views.UserLogOutView.as_view(), name='user_logout'),
    # front end customer confirm booking page 
    path('confirm-booking/', views.ConfirmBookingView.as_view(), name='confirm_booking'),
    #TwentyFourHoursDealsView
    path('twenty-four-deals/', views.TwentyFourHoursDealsView.as_view(), name='twenty-four-deals'),
    # under construction page 
    # about us
    path('about-us/', views.AboutUsView.as_view(), name='about_us'),
    # contact us
    path('contact-us/', views.ContactUsView.as_view(), name='contact_us'),
    # faq
    path('faq/', views.FaqView.as_view(), name='faq'),
    # blog
    path('blog/', views.BlogView.as_view(), name='blog'),
    # press
    path('press/', views.PressView.as_view(), name='press'),
    # terms of use
    path('terms-of-use/', views.TermsOfUseView.as_view(), name='terms_of_use'),
    # give us feedbacks
    path('give-feedback/', views.GiveFeedbackView.as_view(), name='give_us_feedback'),
    # help center
    path('help-center/', views.HelpCenterView.as_view(), name='help_center'),
    # privacy policy
    path('privacy-policy/', views.PrivacyPolicyView.as_view(), name='privacy_policy'),
    # events
    path('event/', views.EventFrontEndView.as_view(), name='event'),
    # services
    path('services/', views.ServicesFrontEndView.as_view(), name='services'),
    # hotels
    path('hotel/', views.HotelsFrontEndView.as_view(), name='hotel'),
    # login from mobile device
    path('login/', views.UserLoginFromMobileDeviceView.as_view(), name='mobile_login'),
    # signup from mobile device
    path('register/', views.UserRegistrationFromMobileDeviceView.as_view(), name='mobile_signup'),
    # user profile view
    path('profile/', views.UserProfileView.as_view(), name='profile'),
    # frontend views urls end

    # admin panel view urls start
    path('admin-login/', views.AdminLoginView.as_view(), name='admin_login'),
    path('dashboard/', views.DashboardView.as_view(), name='dashboard'),
    path('user-types/', views.UserTypeView.as_view(), name='user_type'),
    path('hotels/', views.HotelView.as_view(), name='hotels'),
    path('rooms/', views.RoomView.as_view(), name='rooms'),
    path('offer-types/', views.OfferTypeView.as_view(), name='offer-types'),
    path('offer-max-amounts/', views.OfferMaxAmountView.as_view(), name='offer-max-amounts'),
    path('offers/', views.OfferView.as_view(), name='offers'),
    path('coupon/', views.CuponView.as_view(), name='coupon'),
    path('giftcard/', views.GiftCardView.as_view(), name='giftcard'),
    path('events/', views.EventView.as_view(), name='events'),
    path('foodmenu/', views.FoodMenuView.as_view(), name='foodmenu'),
    path('touristspot/', views.TouristSpotView.as_view(), name='touristspot'),
    path('hotel-gallery/', views.HotelGallery.as_view(), name='hotel_gallery'),
    path('booking/', views.BookingView.as_view(), name='booking'),
    path('packages/', views.PackageView.as_view(), name='packages'),
    path('carts/', views.CartView.as_view(), name='carts'),
    path('facilites/', views.FacilitesView.as_view(), name='facilites'),
    path('facilites-room/', views.FacilitesGroupView.as_view(), name='facilites-room'),
    path('hotel-facilites/', views.HotelFacilitesView.as_view(), name='hotel-facilites'),
    #TwentyFourHoursDealsPorzotokAppView
    path('porzotok-deals/', views.TwentyFourHoursDealsPorzotokAppView.as_view(), name='porzotok-deals'),
    #TwentyFourHoursDealsHotelView
    path('hotel-deals/', views.TwentyFourHoursDealsHotelView.as_view(), name='hotel-deals'),
    # admin panel view urls end
]

porzotokProject/templates/backEnd/24hoursdeals/porzotok_24_hours_deals.html
{% extends 'backEnd/admin_layouts.html' %}
{% load static %}

{% block title %}Porzotok || 24 Hours Deals{% endblock  %}

{% block custom_css %}
    <!-- scrollspyNav css -->
    <link rel="stylesheet" type="text/css" href="{% static 'backEnd/assets/css/scrollspyNav.css' %}">
    <!-- breadcrumb css -->
    <link rel="stylesheet" type="text/css" href="{% static 'backEnd/assets/css/elements/miscellaneous.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'backEnd/assets/css/elements/breadcrumb.css' %}">
    <!-- data table -->
    <link rel="stylesheet" type="text/css" href="{% static 'backEnd/plugins/table/datatable/datatables.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'backEnd/plugins/table/datatable/dt-global_style.css' %}">
    <!-- toast -->
    <link href="{% static 'backEnd/plugins/notification/snackbar/snackbar.min.css' %}" rel="stylesheet" type="text/css" />
    <!-- END PAGE LEVEL PLUGINS -->
{% endblock %}

{% block main_content %}

<div class="row mt-2 ml-2">
    <div class="col-12">
        <nav class="breadcrumb-two" aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'webapp:dashboard' %}">Home</a></li>
                <li class="breadcrumb-item active"><a href="javascript:void(0);">24 Hours Deals</a></li>
                <li class="breadcrumb-item" aria-current="page"><a href="javascript:void(0);">24 Hours Deals</a></li>
            </ol>
        </nav>
    </div>
</div>


<!-- table start -->
<div id="app" class="layout-px-spacing">

    <div class="row layout-top-spacing">

        <!-- add form start -->
        <div class="col-lg-12 layout-spacing">
            <div class="statbox widget box box-shadow">
                <div class="widget-header">
                    <div class="row">
                        <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                            <h4>Add 24 Hours Deals</h4>
                        </div>                                                                        
                    </div>
                </div>
                <div class="widget-content widget-content-area">

                    <!-- add room -->
                    <form @submit.prevent="add24HoursDeals" id="add24HoursDealsForm" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="form-group col-md-12">
                                <label for="TwentyFourDealName">Twenty Four Hours Deals Name</label>
                                <input type="text" class="form-control" v-model="twenty_four_hours_deals_name" id="TwentyFourDealName" placeholder="Enter Twenty Four Hours Deals Name">
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="roomImage">Room Image</label>
                                <input @change="onFileChange" type="file" class="form-control" name="image" id="roomImage" multiple />
                            </div>
                            
                        </div>

                        <div class="n-chk">
                            <label>
                              <input v-model="is_active" type="checkbox" id="isActive" class="new-control-input" checked>
                              <span>Is Active</span>
                            </label>
                        </div>
                        
                      <button type="submit" class="btn btn-primary mt-3">Add 24 Hours Deals</button>
                    </form>
                </div>
            </div>
        </div>

        <!-- add form end -->
    
        <!-- table start -->
        <div class="col-xl-12 col-lg-12 col-sm-12  layout-spacing">
            <h4 class="d-inline">Room List</h4>
  
            <div class="widget-content widget-content-area br-6 mt-4">
                <div class="table-responsive mb-4 mt-4">
                    <table id="dataTableContent" class="table table-hover" style="width:100%">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>24 Hours Deals Name</th>
                                <th>Status</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>

                            <tr v-for="pdeals in allTwentyFourHoursDealsPorzotoks" :key="pdeals.twenty_four_hours_deals_porzotok_id">
                                <td>${ pdeals.twenty_four_hours_deals_porzotok_id }</td>
                                <td>${ pdeals.twenty_four_hours_deals_name }</td>
                                <td>${ pdeals.is_active }</td>

                                <td class="text-center">
                                    <a @click.prevent="editRoom(room.room_id);" href="javascript:void(0);" class="bs-tooltip" data-toggle="tooltip" data-placement="top" title="Edit" data-original-title="Edit"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-edit-2 p-1 br-6 mb-1"><path d="M17 3a2.828 2.828 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5L17 3z"></path></svg></a>
                                    &nbsp;
                                    <a @click.prevent="deleteRoom(room.room_id);" href="javascript:void(0);" class="bs-tooltip" data-toggle="tooltip" data-placement="top" title="Delete" data-original-title="Delete"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-trash p-1 br-6 mb-1"><polyline points="3 6 5 6 21 6"></polyline><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path></svg></a>
                                </td>
                            </tr>

                            
                        </tbody>
                        
                    </table>
                </div>
            </div>
        </div>
        <!-- table end -->

    </div>
    <div v-if="error" class="snackbar-container  snackbar-pos top-right" style="width: auto; background: rgb(59, 63, 92); opacity: 1;">
        <p style="margin: 0px; padding: 0px; color: rgb(255, 255, 255); font-size: 14px; font-weight: 300; line-height: 1em;">${msg}</p>
        <button class="action" style="color: rgb(37, 213, 228);">Dismiss</button>
    </div>
</div>
<!-- table end -->
{% endblock %}

{% block custom_js %}
    <script src="{% static 'backEnd/plugins/highlight/highlight.pack.js' %}"></script>
    <!-- data table script -->
    <script src="{% static 'backEnd/plugins/table/datatable/datatables.js' %}"></script>
    <script>
        $('#dataTableContent').DataTable({
            "oLanguage": {
                "oPaginate": { "sPrevious": '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-left"><line x1="19" y1="12" x2="5" y2="12"></line><polyline points="12 19 5 12 12 5"></polyline></svg>', "sNext": '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-right"><line x1="5" y1="12" x2="19" y2="12"></line><polyline points="12 5 19 12 12 19"></polyline></svg>' },
                "sInfo": "Showing page _PAGE_ of _PAGES_",
                "sSearch": '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-search"><circle cx="11" cy="11" r="8"></circle><line x1="21" y1="21" x2="16.65" y2="16.65"></line></svg>',
                "sSearchPlaceholder": "Search",
               "sLengthMenu": "Results :  _MENU_",
            },
            "stripeClasses": [],
            "lengthMenu": [10, 15, 25, 50],
            "pageLength": 10 
        });

        $('.top-right').click(function() {
            Snackbar.show({
                text: 'Example notification text.',
                pos: 'top-right'
            });
        });

    </script>
     <!-- BEGIN PAGE LEVEL PLUGINS -->
    <script src="{% static 'backEnd/assets/js/scrollspyNav.js' %}"></script>
    <!-- toastr -->
    <script src="{% static 'backEnd/plugins/notification/snackbar/snackbar.min.js' %}"></script>
    <!-- END PAGE LEVEL PLUGINS -->

    <!--  BEGIN CUSTOM SCRIPTS FILE  -->
    <script src="{% static 'backEnd/assets/js/components/notification/custom-snackbar.js' %}"></script>

    <!--  END CUSTOM SCRIPTS FILE  -->
    <!-- vue js scripts start -->
    <script type="text/javascript">

        new Vue({
            el: '#app',
            delimiters: ['${','}'],
            data: {
                allTwentyFourHoursDealsPorzotoks : [],
                twenty_four_hours_deals_name : null,
                image : '',
                is_active : null,
                msg : '',
                error: '',
                update_val : '',
                click_event : false,
                update_bool : false,
            },
            mounted: function() {
                this.getAllTwentyFourHoursDealsPorzotoks();
            },
            methods: {
                add24HoursDeals: function(event) {
                    let form_data = new FormData();

                    form_data.append('twenty_four_hours_deals_name', this.twenty_four_hours_deals_name);
                    form_data.append('is_active', this.is_active);

                    for( var i = 0; i < this.image.length; i++ ){
                      let file = this.image[i];
                      form_data.append('image', file);
                    }

                    this.$http.post(`/api/porzotok-deals/`, form_data)
                        .then((resp) => {
                            console.log(resp.data);
                            
                            if (resp.status == 201 || resp.status == 200) {
                                this.error = true
                                this.msg = resp.data.message;
                                
                                // back to top when edit
                                let scrollingElement = (document.scrollingElement || document.body);
                                $(scrollingElement).animate({
                                    scrollTop: 0
                                }, 500);
                                // get all hotels
                                this.getAllTwentyFourHoursDealsPorzotoks();
                            }
                        })
                        .catch((err) => {
                            console.log(err);
                        })
                },
                
                getAllTwentyFourHoursDealsPorzotoks: function() {
                    this.$http.get(`/api/porzotok-deals/`)
                        .then((resp) => {
                            this.allTwentyFourHoursDealsPorzotoks = resp.data.data;
                        })
                        .catch((err) => {
                            console.log(err);
                        })
                },

                onFileChange(event) {
                    this.image = event.target.files;
                },

            }
        });
    </script>
    <!-- vue js scripts end -->
   

{% endblock %}